# standard
theme: jekyll-theme-cayman
exclude: [draft, standard]
baseurl: ''

# BBF-specific
bbf_version: TR-454-v1.0.0-take2
bbf_title: Broadband Forum YANG Modules
bbf_tagline: A set of YANG modules for managing access networks
bbf_google_analytics_tag: ''
