# standard
theme: jekyll-theme-cayman
exclude: [draft, standard]
baseurl: ''

# BBF-specific
bbf_version: TR-355-v1.3.0+TR-383-v1.3.0+TR-385-v2.0.0
bbf_title: Broadband Forum YANG Modules
bbf_tagline: A set of YANG modules for managing access networks
bbf_google_analytics_tag: ''
